<?php

namespace App\Command;

use App\Service\MailService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

class SendMailCompanyHajj2025Command extends Command
{
    protected static $defaultName = 'app:send-email-company-haj';

    private EntityManagerInterface $entityManager;
    private MailService $mailService;

    public function __construct(
        EntityManagerInterface $entityManager,
        MailService $mailService

    )
    {
        parent::__construct();
        $this->entityManager = $entityManager;
        $this->mailService = $mailService;
    }

    protected function configure(): void
    {
        $this
            ->setName('app:send-email-company-haj')
            ->setDescription('Send email to company HAJ');
    }


    /**
     * @throws \DateMalformedStringException
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $contacts = [
           // ['id'=> 1,'fullName'=> 'Issam LAMMRI', 'email'=> 'issamlamri34000@gmail.com'],
            ['id'=> 1,'fullName'=> 'Issam LAMMRI', 'email'=> 'issamlammri5@gmail.com'],
//            ['id'=> 0,'fullName'=> 'Khaoula CHEBIR', 'email'=> 'chebirkhaoula@yahoo.com'],
           // ['id'=> 0,'fullName'=> 'Souleymen sahnoun', 'email'=> 'souleymen.sahnoun@gmail.com'],
        ];

        $contacts1 = [
            /*['id'=> 0,'fullName'=> 'Khaoula CHEBIR', 'email'=> 'chebirkhaoula@yahoo.com'],
            [ 'id'=> 1, 'fullName'=> 'ABADA MOKTAR', 'email'=> 'rhiou030577@gmail.com'],
            [ 'id'=> 2, 'fullName'=> 'Addad tayeb', 'email'=> 'tayebaddad@live.fr'],
            [ 'id'=> 3, 'fullName'=> 'AFYF Saïd', 'email'=> 'daraouiloubna@gmail.com'],
            [ 'id'=> 4, 'fullName'=> 'AHCENE Djaballah Badreddine', 'email'=> 'houdaeurocrystal@gmail.com'],
            [ 'id'=> 5, 'fullName'=> 'Ahcene djaballah Sabri', 'email'=> 'nazimo38000@gmail.com'],
            [ 'id'=> 6, 'fullName'=> 'AID Hafid', 'email'=> 'eurassier2009@yahoo.fr'],
            [ 'id'=> 7, 'fullName'=> 'Ait lhoussaine Mohamed', 'email'=> 'mohamed.aitkiriout@live.fr'],
            [ 'id'=> 8, 'fullName'=> 'Mohammed', 'email'=> 'moha-586@hotmail.com'],
            [ 'id'=> 9, 'fullName'=> 'Amir Djamel', 'email'=> 'djamelamir93@gmail.com'],
            [ 'id'=> 10, 'fullName'=> 'Amrani boukhatem', 'email'=> 'boka_dz@hotmail.fr'],
            [ 'id'=> 11, 'fullName'=> 'Arroug lahcen', 'email'=> 'arroughalima@yahoo.com'],
            [ 'id'=> 12, 'fullName'=> 'Assidi Abdeljelil', 'email'=> 'abdel.assidi@gmail.com'],
            [ 'id'=> 13, 'fullName'=> 'Assiev Andarbek', 'email'=> 'grenobledojo@gmail.com'],
            [ 'id'=> 14, 'fullName'=> 'AZZAKHNINI MESTAPHA', 'email'=> 'mariemazzakhnini@gmail.com'],
            [ 'id'=> 15, 'fullName'=> 'BAADACHE SAMIR', 'email'=> 'samir.baadache@gmail.com'],
            [ 'id'=> 16, 'fullName'=> 'Baida Mustapha', 'email'=> 'mustaphauae@gmail.com'],
            [ 'id'=> 17, 'fullName'=> 'BECHKOUR lyes', 'email'=> 'elias1977@live.fr'],
            [ 'id'=> 18, 'fullName'=> 'BEGHILA NORDINE', 'email'=> 'nordine23annaba@gmail.com'],
            [ 'id'=> 19, 'fullName'=> 'Behiri khaled', 'email'=> 'ayia.4070@gmail.com'],
            [ 'id'=> 20, 'fullName'=> 'med amine bejaoui', 'email'=> 'aounigrenoble@gmail.com'],
            [ 'id'=> 21, 'fullName'=> 'BEL HADJ AHMED', 'email'=> 'hamed_tssr@yahoo.fr'],
            [ 'id'=> 22, 'fullName'=> 'Belakhssaiss said', 'email'=> 'Ad_malherbe@outlook.fr'],
            [ 'id'=> 23, 'fullName'=> 'Belanig fathi', 'email'=> 'belanigfathi93@gmail.com'],
            [ 'id'=> 24, 'fullName'=> 'Belhadj ali', 'email'=> 'samirabenali37@gmail.com'],
            [ 'id'=> 25, 'fullName'=> 'Belhadj', 'email'=> 'yamina_feryel@yahoo.fr'],
            [ 'id'=> 26, 'fullName'=> 'Belhadji Ahmed', 'email'=> 'belhadji.amed@gmail.com'],
            [ 'id'=> 27, 'fullName'=> 'Benaboura kamal', 'email'=> 'izem-ju@hotmail.fr'],
            [ 'id'=> 28, 'fullName'=> 'Benaissa lachemi', 'email'=> 'Blachemibiskra72@gmail.com'],
            [ 'id'=> 29, 'fullName'=> 'Benali ahmed', 'email'=> 'echirolles23@gmail.com'],
            [ 'id'=> 30, 'fullName'=> 'Benameur samir', 'email'=> 'samir.benameur38@gmail.com'],
            [ 'id'=> 31, 'fullName'=> 'Benatitallah hichem', 'email'=> 'hichem321@hotmail.fr'],
            [ 'id'=> 32, 'fullName'=> 'Benayache sabar', 'email'=> 'Sabar.benayache@yahoo.fr'],
            [ 'id'=> 33, 'fullName'=> 'Benchaikh said', 'email'=> 'saidbelgium@hotmail.com'],
            [ 'id'=> 34, 'fullName'=> 'Bendoucha gharib', 'email'=> 'sonia.59@laposte.net'],
            [ 'id'=> 35, 'fullName'=> 'Benkhaoua Badis', 'email'=> 'badis1975@hotmail.fr'],
            [ 'id'=> 36, 'fullName'=> 'Benkhrourou Mourad', 'email'=> 'benk.grenoble66@gmail.com'],
            [ 'id'=> 37, 'fullName'=> 'Benkrama mohammed', 'email'=> 'mohammed_benkrama@msn.com'],
            [ 'id'=> 38, 'fullName'=> 'Benseghir Mohamed', 'email'=> 'm.ben73@laposte.net'],
            [ 'id'=> 39, 'fullName'=> 'Bensoucha lakhdar', 'email'=> 'BENSOUCHA.LAKHDER@HOTMAIL.COM'],
            [ 'id'=> 40, 'fullName'=> 'Benyahia abdelmalek', 'email'=> 'benyahia2@yahoo.fr'],
            [ 'id'=> 42, 'fullName'=> 'Benyettou Brahim', 'email'=> 'saliha1304@outlook.fr'],
            [ 'id'=> 43, 'fullName'=> 'Beya slah', 'email'=> 'oumaima38@hotmail.fr'],
            [ 'id'=> 44, 'fullName'=> 'Bikarane brahim', 'email'=> 'bbikarane5@gmail.com'],
            [ 'id'=> 45, 'fullName'=> 'BIRCH Maamar', 'email'=> 'maamar.birch@etam-technologie.com'],
            [ 'id'=> 46, 'fullName'=> 'BENOMAR HAKIM', 'email'=> 'f_213@hotmail.fr'],
            [ 'id'=> 47, 'fullName'=> 'BOUALIRABAH', 'email'=> 'ourida.bouali@yahoo.com'],
            [ 'id'=> 48, 'fullName'=> 'Bouauin elhossain', 'email'=> 'hossbob151@gmail.com'],
            [ 'id'=> 49, 'fullName'=> 'Bouauin elhossain', 'email'=> 'Hossbob151@gmail.com'],
            [ 'id'=> 50, 'fullName'=> 'Mohieddine Boubtane', 'email'=> 'boubtane.m@gmail.com'],
            [ 'id'=> 51, 'fullName'=> 'Boucif nasreddine', 'email'=> 'Opti_que@yahoo.fr'],
            [ 'id'=> 52, 'fullName'=> 'Boucif nasreddine', 'email'=> 'boucifabdou@yahoo.fr'],
            [ 'id'=> 53, 'fullName'=> 'Boudia David', 'email'=> 'n.nori@live.fr'],
            [ 'id'=> 54, 'fullName'=> 'Boufedah badici Ali', 'email'=> 'naouel.korichi38@gmail.com'],
            [ 'id'=> 55, 'fullName'=> 'Boughedir Mehdi', 'email'=> 'linda.boughedir@hotmail.fr'],
            [ 'id'=> 56, 'fullName'=> 'Boughraira Nadhir', 'email'=> 'nboughraira@yahoo.com'],
            [ 'id'=> 57, 'fullName'=> 'Bouhalla Ahmed', 'email'=> 'ahmed.bouhalla@hotmail.com'],
            [ 'id'=> 58, 'fullName'=> 'Bouissa Said', 'email'=> 'bouissa_s@hotmail.fr'],
            [ 'id'=> 59, 'fullName'=> 'Bouissa khalid', 'email'=> 'khalidbouissa@live.fr'],
            [ 'id'=> 60, 'fullName'=> 'Boukelsous Said', 'email'=> 'saidboukelsous@yahoo.fr'],
            [ 'id'=> 61, 'fullName'=> 'Boukersi nasser', 'email'=> 'makhloumoi@gmail.com'],
            [ 'id'=> 62, 'fullName'=> 'Boukhennoufa bilal', 'email'=> 'bilou.38@hotmail.fr'],
            [ 'id'=> 63, 'fullName'=> 'Boulmedais mohamed lamine', 'email'=> 'Bimo_amine2003@hotmail.com'],
            [ 'id'=> 64, 'fullName'=> 'Boumahdi messaoud', 'email'=> 'messaoud.boumahdi@gmail.com'],
            [ 'id'=> 65, 'fullName'=> 'Boumendjel Abdelmadjid', 'email'=> 'abdelmadjid.boumendjel@gmail.com'],
            [ 'id'=> 66, 'fullName'=> 'Bouslimi jamil', 'email'=> 'ibouslimi@hotmail.fr'],
            [ 'id'=> 67, 'fullName'=> 'Boutahra zidane', 'email'=> 'Zidanebaraka722@gmail.com'],
            [ 'id'=> 68, 'fullName'=> 'Boutahra Toufik', 'email'=> 'faycal38100@yahoo.com'],
            [ 'id'=> 69, 'fullName'=> 'Bouti belkhir', 'email'=> 'boutibelkhir@yaho.fr'],
            [ 'id'=> 70, 'fullName'=> 'Bouti belkhir', 'email'=> 'boutibelkhir@yahoo.fr'],
            [ 'id'=> 71, 'fullName'=> 'Bouyala karim', 'email'=> 'ouzwiren@hotmail.fr'],
            [ 'id'=> 72, 'fullName'=> 'Bouziane Derradji', 'email'=> 'a-yousra@hotmail.fr'],
            [ 'id'=> 73, 'fullName'=> 'Bouzzine', 'email'=> 'ahmed38@hotmail.fr'],
            [ 'id'=> 74, 'fullName'=> 'Bouzzine salim', 'email'=> 'salimbouzzine@gmail.com'],
            [ 'id'=> 75, 'fullName'=> 'Bouzzine Najim', 'email'=> 'najim.bouzzine@gmail.com'],
            [ 'id'=> 76, 'fullName'=> 'Brahimi', 'email'=> 'Brahimi.rafik@outlook.fr'],
            [ 'id'=> 77, 'fullName'=> 'Briek Malik', 'email'=> 'wahibabriek@gmail.com'],
            [ 'id'=> 78, 'fullName'=> 'Chadli Fayçal', 'email'=> 'faycal.chadli4444@gmail.com'],
            [ 'id'=> 79, 'fullName'=> 'Chadli faycal', 'email'=> 'faycalinesti@gmail.com'],
            [ 'id'=> 80, 'fullName'=> 'Chakour houari', 'email'=> 'achakour86@gmail.com'],
            [ 'id'=> 81, 'fullName'=> 'Chaouch abderrahmane', 'email'=> 'chaouch38@hotmail.fr'],
            [ 'id'=> 82, 'fullName'=> 'Charef Abdelkader', 'email'=> 'charefkader@yahoo.fr'],
            [ 'id'=> 83, 'fullName'=> 'Charrad Belkacem', 'email'=> 'chac64272@gmail.com'],
            [ 'id'=> 84, 'fullName'=> 'Cheklam toufik', 'email'=> 'toufik53@live.fr'],
            [ 'id'=> 85, 'fullName'=> 'Chekri smaine', 'email'=> 'chekri_s@yahoo.fr'],
            [ 'id'=> 86, 'fullName'=> 'Cherfi Tarek', 'email'=> 'djamilayn.mesba@gmail.com'],
            [ 'id'=> 87, 'fullName'=> 'Cheriet Hamou', 'email'=> 'zakicheriet@live.fr'],
            [ 'id'=> 88, 'fullName'=> 'Chikh houari', 'email'=> 'Warielas@hotmail.fr'],
            [ 'id'=> 89, 'fullName'=> 'Chtioui zammit Tarek', 'email'=> 'tarekchtioui38@gmail.com'],
            [ 'id'=> 90, 'fullName'=> 'Ciritci Sinan', 'email'=> 'ciritcisinan@hotmail.com'],
            [ 'id'=> 91, 'fullName'=> 'Dahi Halim', 'email'=> 'dahi@netcourrier.com'],
            [ 'id'=> 92, 'fullName'=> 'dahmani mohamed chaouki', 'email'=> 'fatdah69@gmail.com'],
            [ 'id'=> 93, 'fullName'=> 'Dahouas abdelhamid', 'email'=> 'zayd38100@gmail.com'],
            [ 'id'=> 94, 'fullName'=> 'Dahouas Rabah', 'email'=> 'faudicap@yahoo.com'],
            [ 'id'=> 95, 'fullName'=> 'DAOUD BRIKCI Sid ahmed', 'email'=> 'sid.daoud@free.fr'],
            [ 'id'=> 96, 'fullName'=> 'Debdeb samir', 'email'=> 'debdebsamir@gmail.com'],
            [ 'id'=> 97, 'fullName'=> 'Debib khaled', 'email'=> 'k.debib@gmail.com'],
            [ 'id'=> 98, 'fullName'=> 'debit atef', 'email'=> 'atefdebit@gmail.com'],
            [ 'id'=> 99, 'fullName'=> 'Dellaa Kaddour', 'email'=> 'dellaakaddour@gmail.com'],
            [ 'id'=> 101, 'fullName'=> 'Derares tayeb', 'email'=> 'Tayeb.derares@gmail.com'],
            [ 'id'=> 102, 'fullName'=> 'Diakhaby Mohamed Lamine', 'email'=> 'sdiakhaby38@gmail.com'],
            [ 'id'=> 104, 'fullName'=> 'Diakhaby sankoumba', 'email'=> 'sankoumbaca28@gmail.com'],
            [ 'id'=> 105, 'fullName'=> 'DJAZOULI', 'email'=> 'djazouli@esrf.fr'],
            [ 'id'=> 106, 'fullName'=> 'DJEDDI Mounir', 'email'=> 'mounir_djeddi@outlook.com'],
            [ 'id'=> 107, 'fullName'=> 'Djelailia Toufik', 'email'=> 'toufik.anas2016@gmail.com'],
            [ 'id'=> 108, 'fullName'=> 'Djelili Hakim', 'email'=> 'kimou_1977@hotmail.fr'],
            [ 'id'=> 109, 'fullName'=> 'DJELLOUL mazouz Mokhtar', 'email'=> 'mokhtargf38@gmail.com'],
            [ 'id'=> 110, 'fullName'=> 'Doukali rachid', 'email'=> 'Rachid4838@gmail.com'],
            [ 'id'=> 111, 'fullName'=> 'Doukali rachid', 'email'=> 'rachid3848@hotmail.fr'],
            [ 'id'=> 112, 'fullName'=> 'El Aallami Faissal', 'email'=> 'elfay@outlook.com'],
            [ 'id'=> 113, 'fullName'=> 'El Hasni yahya', 'email'=> 'lyahm@hotmail.com'],
            [ 'id'=> 114, 'fullName'=> 'El mimouni Abdelkader', 'email'=> 'Abdel_3838@hotmail.fr'],
            [ 'id'=> 115, 'fullName'=> 'El Moumni Mostafa', 'email'=> 'mostafaelms@gmail.com'],
            [ 'id'=> 116, 'fullName'=> 'EL RHAFFARI REDA', 'email'=> 'r_maroc@live.fr'],
            [ 'id'=> 117, 'fullName'=> 'Mohammed El yaacoubi', 'email'=> 'yacoubi1981@hotmail.com'],
            [ 'id'=> 118, 'fullName'=> 'Farah ali', 'email'=> 'farah38ali@gmail.com'],
            [ 'id'=> 119, 'fullName'=> 'Farah mohamed', 'email'=> 'farah.mohamed38@gmail.com'],
            [ 'id'=> 120, 'fullName'=> 'Ferdji', 'email'=> 'ferdjimohamed8@gmail.com'],
            [ 'id'=> 121, 'fullName'=> 'Gasmi Ali', 'email'=> 'mig.importexport@yahoo.fr'],
            [ 'id'=> 122, 'fullName'=> 'Gherbi abdelghani', 'email'=> 'choayb.ishaq@hotmail.com'],
            [ 'id'=> 123, 'fullName'=> 'GHILOUFI Salem', 'email'=> 'ghiloufisalem@gmail.com'],
            [ 'id'=> 124, 'fullName'=> 'Ghoulem djelloul', 'email'=> 'djelîx@hotmail.fr'],
            [ 'id'=> 125, 'fullName'=> 'GOURARI Neguib', 'email'=> 'ne.ij@live.fr'],
            [ 'id'=> 126, 'fullName'=> 'GRANA NASSIR', 'email'=> 'nassirgrana@yahoo.fr'],
            [ 'id'=> 127, 'fullName'=> 'Guedouar Tewfik', 'email'=> 'gtds@hotmail.fr'],
            [ 'id'=> 128, 'fullName'=> 'Hadj mokhnache larbi', 'email'=> 'Bouzidhadj@gmail.com'],
            [ 'id'=> 129, 'fullName'=> 'Hakach Mustapha', 'email'=> 'hakmoss16@gmail.com'],
            [ 'id'=> 130, 'fullName'=> 'Hamada Yamine', 'email'=> 'Yamineh38@gmail.com'],
            [ 'id'=> 131, 'fullName'=> 'Hamadi ali', 'email'=> 'alimene10@hotmail.fr'],
            [ 'id'=> 132, 'fullName'=> 'Hamadi ali', 'email'=> 'Alimene10@hotmail.fr'],
            [ 'id'=> 133, 'fullName'=> 'HAMI Ali', 'email'=> 'Ali.anissa@outlook.fr'],
            [ 'id'=> 134, 'fullName'=> 'Hammami fouad', 'email'=> 'guessoum_amina@yahoo.com'],
            [ 'id'=> 135, 'fullName'=> 'Hamoudi hichem', 'email'=> 'hichem.hamoudi@hotmail.fr'],
            [ 'id'=> 136, 'fullName'=> 'Haoirich Mustapha', 'email'=> 'haoirich.mustapha@gmail.com'],
            [ 'id'=> 137, 'fullName'=> 'Harabi Ouahid', 'email'=> 'Wahid.hd@outlook.fr'],
            [ 'id'=> 138, 'fullName'=> 'Harabi ouahid', 'email'=> 'Wa.hd@outlook.fr'],
            [ 'id'=> 139, 'fullName'=> 'Harrag Mohammed', 'email'=> 'nad.zerr@hotmail.fr'],
            [ 'id'=> 140, 'fullName'=> 'Abdelkrim', 'email'=> 'amarhebbachi82@gmail.com'],
            [ 'id'=> 141, 'fullName'=> 'Helaoui Amar', 'email'=> 'helamr1011@gmail.com'],
            [ 'id'=> 142, 'fullName'=> 'Hemaizia, Chadli', 'email'=> 'chad38@live.fr'],
            [ 'id'=> 143, 'fullName'=> 'Kaidat tarek', 'email'=> 'Naouel.korichi38@gmail.com'],
            [ 'id'=> 144, 'fullName'=> 'Karrouby sofien', 'email'=> 'karroubys@yahoo.fr'],
            [ 'id'=> 145, 'fullName'=> 'Ammar kebaili', 'email'=> 'kebailikhedidja31@gmail.com'],
            [ 'id'=> 146, 'fullName'=> 'Kerfah Slimane', 'email'=> 'benslimane@gmail.com'],
            [ 'id'=> 147, 'fullName'=> 'Kermali Abdelwahab', 'email'=> 'ismailker70@gmail.com'],
            [ 'id'=> 148, 'fullName'=> 'KERMALI abdelkader', 'email'=> 'safia2502@gmail.com'],
            [ 'id'=> 149, 'fullName'=> 'Idir', 'email'=> 'iddirdz@gmail.com'],
            [ 'id'=> 150, 'fullName'=> 'Ketrouci Abdelkader', 'email'=> 'farah38600@outlook.fr'],
            [ 'id'=> 151, 'fullName'=> 'Ketroussi abdelkader', 'email'=> 'Kamelsonatrash@gmail.com'],
            [ 'id'=> 152, 'fullName'=> 'Khabizayev Movsar', 'email'=> 'khabizayev@gmail.com'],
            [ 'id'=> 153, 'fullName'=> 'Khadim Mahfoud', 'email'=> 'abekhadim02@gmail.com'],
            [ 'id'=> 154, 'fullName'=> 'Khalissa kais', 'email'=> 'khalissakais@gmail.com'],
            [ 'id'=> 155, 'fullName'=> 'Kheddim bouabdallah', 'email'=> 'coucou38@gmx.fr'],
            [ 'id'=> 156, 'fullName'=> 'Kherroubi boumeddah hocine', 'email'=> 'hocineiyadassil@gmail.com'],
            [ 'id'=> 157, 'fullName'=> 'Khiat ahmed', 'email'=> 'ishakabdraaak@gmail.com'],
            [ 'id'=> 158, 'fullName'=> 'Khoualdi Taoufik', 'email'=> 'khoualdit@yahoo.fr'],
            [ 'id'=> 159, 'fullName'=> 'Korichi Ali', 'email'=> 'korichiali98@gmail.com'],
            [ 'id'=> 160, 'fullName'=> 'Koroghli habib', 'email'=> 'mayssem38@live.fr'],
            [ 'id'=> 161, 'fullName'=> 'Koudri Abdellatif', 'email'=> 'michelgakson2@gmail.com'],
            [ 'id'=> 162, 'fullName'=> 'Kraim karima', 'email'=> 'lougine2009@hotmail.fr'],
            [ 'id'=> 163, 'fullName'=> 'Krour Mohamed', 'email'=> 'Mohamedkrour076@gmail.com'],
            [ 'id'=> 164, 'fullName'=> 'Lachhab Faouzi', 'email'=> 'Faouzi.lachhab@gmail.com'],
            [ 'id'=> 165, 'fullName'=> 'Lahgazi alaoui yassine', 'email'=> 'yasml09.yla@gmail.com'],
            [ 'id'=> 166, 'fullName'=> 'Lakhoulfi Mohammed', 'email'=> 'LakhloufiMohammed@gmail.com'],
            [ 'id'=> 167, 'fullName'=> 'Magatmirzoev Rizvan', 'email'=> 'dinarotgang@gmail.com'],
            [ 'id'=> 168, 'fullName'=> 'Magomadov Aslanbek', 'email'=> 'Martanaslan1988@gmail.com'],
            [ 'id'=> 169, 'fullName'=> 'Maguenni abdelhadi', 'email'=> 'abdelhadi.maguenni@gmail.com'],
            [ 'id'=> 170, 'fullName'=> 'Mallek laradj', 'email'=> 'laradj.mallek@yahoo.com'],
            [ 'id'=> 171, 'fullName'=> 'Medjahed mahi', 'email'=> 'medjahedmahi38400@gail.com'],
            [ 'id'=> 172, 'fullName'=> 'Meftah Tewfik', 'email'=> 'tewfik.meftah@gmail.com'],
            [ 'id'=> 173, 'fullName'=> 'Mendour salah', 'email'=> 'Salahock@hotmail.it'],
            [ 'id'=> 174, 'fullName'=> 'Meradji Hicham', 'email'=> 'hicham04meradji@gmail.com'],
            [ 'id'=> 175, 'fullName'=> 'Mesbah mokhtar', 'email'=> 'mesbah.mokhtar@hotmail.fr'],
            [ 'id'=> 176, 'fullName'=> 'Mesbah Sofiane', 'email'=> 'sofiane3808@gmail.com'],
            [ 'id'=> 177, 'fullName'=> 'MOKADEM', 'email'=> 'macadam_sidali@yahoo.fr'],
            [ 'id'=> 178, 'fullName'=> 'Sanaa el ahrache', 'email'=> 'Sabrineaya12@gmail.com'],
            [ 'id'=> 179, 'fullName'=> 'Nadif Moukhtar', 'email'=> 'nadif.moukhtar@gmail.com'],
            [ 'id'=> 180, 'fullName'=> 'Kamal nahasse', 'email'=> 'Kamal.nahasse@gmail.com'],
            [ 'id'=> 181, 'fullName'=> 'Nait Yahia Mahmoud', 'email'=> 'mahmoud38420@hotmail.fr'],
            [ 'id'=> 182, 'fullName'=> 'Nasra nadir', 'email'=> 'colombe-visir@hotmail.com'],
            [ 'id'=> 183, 'fullName'=> 'Nazar Djamel', 'email'=> 'nezzar_djamel@yahoo.fr'],
            [ 'id'=> 184, 'fullName'=> "N'DIAYE Cheik", 'email'=> 'cheikndiaye@outlook.fr'],
            [ 'id'=> 185, 'fullName'=> 'Nini salma', 'email'=> 'abdel.elahrache84@gmail.com'],
            [ 'id'=> 186, 'fullName'=> 'Ouf yousef', 'email'=> 'zerizer.dalal@hotmail.fr'],
            [ 'id'=> 187, 'fullName'=> 'OUZAA Akim', 'email'=> 'Ouzaa.akim@gmail.com'],
            [ 'id'=> 188, 'fullName'=> 'Rached Hanifi', 'email'=> 'rachedhanifi@gmail.com'],
            [ 'id'=> 189, 'fullName'=> 'Rachedi zoubir', 'email'=> 'Zoubir38@live.fr'],
            [ 'id'=> 190, 'fullName'=> 'Rafrafi anis', 'email'=> 'Rahlaoui.fatiha@gmail.com'],
            [ 'id'=> 191, 'fullName'=> 'RAHMOUN Mohamed', 'email'=> 'rahmoun11@gmail.com'],
            [ 'id'=> 194, 'fullName'=> 'Reffass Mohammed', 'email'=> 'mreffass@yahoo.fr'],
            [ 'id'=> 195, 'fullName'=> 'Reggad Redha', 'email'=> 'd.ouidad@hotmail.fr'],
            [ 'id'=> 196, 'fullName'=> 'Rekiba djamel', 'email'=> 'djamelrebika@gmail.com'],
            [ 'id'=> 197, 'fullName'=> 'Rettab Mohamed', 'email'=> 'mohamedrettab@hotlook.fr'],
            [ 'id'=> 198, 'fullName'=> 'Rettab Mohamed', 'email'=> 'mohamedrettab@outlook.fr'],
            [ 'id'=> 199, 'fullName'=> 'Robaia Oueheb', 'email'=> 'Marley.cat@live.fr'],
            [ 'id'=> 200, 'fullName'=> 'Safra Amor', 'email'=> 'amorsafra@hotmail.fr'],
            [ 'id'=> 201, 'fullName'=> 'Sahi Nacer', 'email'=> 'Nacer.sahi@gmail.com'],
            [ 'id'=> 202, 'fullName'=> 'saidoune redouane', 'email'=> 'r.saidoune38@gmail.com'],
            [ 'id'=> 203, 'fullName'=> 'Salikhov saidsaliakh', 'email'=> 'said.salah1988@gmail.com'],
            [ 'id'=> 204, 'fullName'=> 'Sammari Mohamed', 'email'=> 'disco25@live.fr'],
            [ 'id'=> 205, 'fullName'=> 'Sansri idriss', 'email'=> 'Mayssandania29@yahoo.com'],
            [ 'id'=> 206, 'fullName'=> 'sayoud messaoud', 'email'=> 'messay2007@hotmail.com'],
            [ 'id'=> 207, 'fullName'=> 'Smiai abdessattar', 'email'=> 'smiaiabdel@hotmail.fr'],
            [ 'id'=> 208, 'fullName'=> 'Souki Fawzi', 'email'=> '2f.nettoyage@gmail.com'],
            [ 'id'=> 209, 'fullName'=> 'Srairi Adel', 'email'=> 'adelsrairi@hotmaill.fr'],
            [ 'id'=> 210, 'fullName'=> 'taoutaou samir', 'email'=> 'taoutaousamir@gmail.com'],
            [ 'id'=> 211, 'fullName'=> 'Tasghat Youcef', 'email'=> 'naouel38@hotmail.fr'],
            [ 'id'=> 212, 'fullName'=> 'Tazghat Kamal', 'email'=> 'kamel_algerie@hotmail.com'],
            [ 'id'=> 213, 'fullName'=> 'tennah mohamed', 'email'=> 'midoumoi909@gmail.com'],
            [ 'id'=> 214, 'fullName'=> 'Teriki mohmed amine', 'email'=> 'teriki-med@hotmail.fr'],
            [ 'id'=> 215, 'fullName'=> 'Torchi', 'email'=> 'dallettes.pro@hotmail.com'],
            [ 'id'=> 216, 'fullName'=> 'wifak el kouri mostafa', 'email'=> 'ibn_ali_1938@outlook.fr'],
            [ 'id'=> 217, 'fullName'=> 'Yaakoubi smail', 'email'=> 'yaakoubi.smail@gmail.com'],
            [ 'id'=> 218, 'fullName'=> 'Yessad Mouloud', 'email'=> 'zebouchihf1989@gmail.com'],
            [ 'id'=> 219, 'fullName'=> 'Ykhlef Abdelhalim', 'email'=> 'kaki38100@yahoo.fr'],
            [ 'id'=> 220, 'fullName'=> 'Younes anis', 'email'=> 'anis.peintre@yahoo.com'],
            [ 'id'=> 221, 'fullName'=> 'Younes anis', 'email'=> 'Anis.peintre@yahoo.com'],
            [ 'id'=> 222, 'fullName'=> 'Ziani Benaissa', 'email'=> 'linaziani20218@gmail.com'],
            [ 'id'=> 223, 'fullName'=> 'Ziani Benaissa', 'email'=> 'linaziani2018@gmail.com'],
            [ 'id'=> 224, 'fullName'=> 'Zitouni Bouabdellah', 'email'=> 'bzitouni2@gmail.com'],
            [ 'id'=> 225, 'fullName'=> 'Azzi Mebarek', 'email'=> 'rahila-azzi@hotmail.fr'],
            [ 'id'=> 226, 'fullName'=> 'Amour charif', 'email'=> 'chafika.rezki@gmail.com'],
            [ 'id'=> 227, 'fullName'=> 'Liacha Bouchra', 'email'=> 'liabouchra63@gmail.com'],
            [ 'id'=> 228, 'fullName'=> 'Bazi Rhizlane', 'email'=> 'garageyahiaoui@gmail.com'],
            [ 'id'=> 229, 'fullName'=> 'Hachemi Djilali ', 'email'=> 'Hananesamira38@gmail.com'],
            [ 'id'=> 230, 'fullName'=> 'Lemhaouel de abdelouaheb', 'email'=> 'abdou.27@hotmail.it'],
            [ 'id'=> 231, 'fullName'=> 'Chaib kiliane', 'email'=> 'kiliane_chaib@icloud.com'],
            [ 'id'=> 232, 'fullName'=> 'Rached Hanifi', 'email'=> 'hasniarached@gmail.com'],
            [ 'id'=> 233, 'fullName'=> 'haroune radouane', 'email'=> 'radouane2708@gmail.com'],
            [ 'id'=> 234, 'fullName'=> 'Guenniche chaouki', 'email'=> 'guennichechaouki@yahoo.fr'],
            [ 'id'=> 235, 'fullName'=> 'Benziar Mohamed', 'email'=> 'mohamedbenziar38@gmail.com'],
            [ 'id'=> 236, 'fullName'=> 'Rechidi mounir', 'email'=> 'hammouhanene07@iCloud.com'],
            [ 'id'=> 237, 'fullName'=> 'Bambo', 'email'=> 'gondobadiaby@yahoo.com'],
            [ 'id'=> 238, 'fullName'=> 'Guenniche Abderrezak', 'email'=> 'guennicheabderrezak@gmail.com'],
            [ 'id'=> 239, 'fullName'=> 'Merimi benyoubka', 'email'=> 'date2019@outlook.fr'],
            [ 'id'=> 240, 'fullName'=> 'Chouayet mongi', 'email'=> 'Mongichouayet@yahoo.fr'],
            [ 'id'=> 241, 'fullName'=> 'Azibi Omar', 'email'=> 'nadorino_99@hotmail.com'],
            [ 'id'=> 242, 'fullName'=> 'Charef serir Hamza', 'email'=> 'ines_assia@hotmail.frp'],
            [ 'id'=> 243, 'fullName'=> 'Majidi el mostafa', 'email'=> 'majidi.elmostafa65@gmail.com'],
            [ 'id'=> 244, 'fullName'=> 'Mammeri youcef', 'email'=> 'youcef.ma@icloud.com'],
            [ 'id'=> 245, 'fullName'=> 'Bensaha', 'email'=> 'bensaha78@yahoo.fr'],
            [ 'id'=> 246, 'fullName'=> 'Anseur billel', 'email'=> 'anseurbillel1511@gmail.com'],
            [ 'id'=> 247, 'fullName'=> 'Benserradj djamel', 'email'=> 'khoualdia.sihem@yahoo.fr'],
            [ 'id'=> 248, 'fullName'=> 'Benserradj karim', 'email'=> 'karimlaichaoui38@gmail.com'],
            [ 'id'=> 249, 'fullName'=> 'Guitoun Hadj', 'email'=> 'ghadj3820@gmail.com'],
            [ 'id'=> 250, 'fullName'=> 'Bouzerara Farouk', 'email'=> 'farouk.bouzerara@gmail.com'],
            [ 'id'=> 251, 'fullName'=> 'Yilmazer sevki', 'email'=> 'sevki.yilmazer@icloud.com'],
            [ 'id'=> 252, 'fullName'=> 'ZAYANI Mohsen', 'email'=> 'sourya.m@hotmail.fr'],
            [ 'id'=> 253, 'fullName'=> 'Raouf', 'email'=> 'boudouraouf@gmail.com'],
            [ 'id'=> 254, 'fullName'=> 'Laichaoui', 'email'=> 'laichaouifathia@gmail.com'],
            [ 'id'=> 255, 'fullName'=> 'Hammoudy Lekbir', 'email'=> 'hammoudylekbir@gmail.com'],
            [ 'id'=> 256, 'fullName'=> 'Medjahed (AS) Mahi', 'email'=> 'malikamedjahed38400@gmail.com'],
            [ 'id'=> 257, 'fullName'=> 'Kassem ALASSAAD', 'email'=> 'kassem.alassaad@gmail.com'],
            [ 'id'=> 258, 'fullName'=> 'benchoula ali', 'email'=> 'moktarbenchoula@hotmail.fr'],
            [ 'id'=> 259, 'fullName'=> 'Benmoussa smain', 'email'=> 'benmoussaamina29@gmail.com'],
            [ 'id'=> 260, 'fullName'=> 'Benali kouchih Redha', 'email'=> 'benalikouchih02@gmail.com'],
            [ 'id'=> 261, 'fullName'=> 'Mouats samir', 'email'=> 'samskikdi@hotmail.com'],
            [ 'id'=> 262, 'fullName'=> 'Mahaman Ibrahim', 'email'=> 'tiamisha01@gmail.com'],
            [ 'id'=> 263, 'fullName'=> 'Arab zakaria', 'email'=> 'zakiayoub2012@gmail.com'],
            [ 'id'=> 264, 'fullName'=> 'MAKHLOUF Laid', 'email'=> 'laid.m38@hotmail.fr'],
            [ 'id'=> 265, 'fullName'=> 'Zitouni hamid', 'email'=> 'zitounih46@gmail.com'],
            [ 'id'=> 266, 'fullName'=> 'Lakehal aziz', 'email'=> 'lakehalaziz@hotmail.fr'],
            [ 'id'=> 267, 'fullName'=> 'KOURI AHMED', 'email'=> 'kouriahmed72@gmail.com'],
            [ 'id'=> 268, 'fullName'=> 'DAKAKNI Maher', 'email'=> 'Maher.dakakni@outlook.com'],
            [ 'id'=> 269, 'fullName'=> 'addala houssam eddine', 'email'=> 'hossfrancy@gmail.com'],
            [ 'id'=> 270, 'fullName'=> 'Trirat abderrahim', 'email'=> 'Abderrahimtrirat@yahoo.com'],
            [ 'id'=> 271, 'fullName'=> 'Benali Adel', 'email'=> 'benaliadel1987@gmail.com'],
            [ 'id'=> 272, 'fullName'=> 'Kaddar Mostafa', 'email'=> 'kaddarmouss@gmail.com'],
            [ 'id'=> 273, 'fullName'=> 'Saad ziad', 'email'=> 'zizou_86@hotmail.com'],
            [ 'id'=> 274, 'fullName'=> 'Sedki Omar', 'email'=> 'omarsedki1988@gmail.com'],
            [ 'id'=> 275, 'fullName'=> 'Adjadj omar', 'email'=> 'omar.boulahia@hotmail.fr'],
            [ 'id'=> 276, 'fullName'=> 'Magomadov aslanbek', 'email'=> 'martanaslan1988@gmail.com'],
            [ 'id'=> 277, 'fullName'=> 'Makhlouf Mounir', 'email'=> 'mak12mou@gmail.com'],
            [ 'id'=> 278, 'fullName'=> 'Niati youcef', 'email'=> 'Ishakyoucef@yahoo.fr'],
            [ 'id'=> 279, 'fullName'=> 'DAOUDI Khaled', 'email'=> 'daoudi.khaled@hotmail.fr'],
            [ 'id'=> 280, 'fullName'=> 'Bouziane khaled', 'email'=> 'salim.azzaba@hotmial.com'],

            [ 'id'=> 281, 'fullName'=> 'Fedila menouer', 'email'=> 'fedilamenouer@gmail.com'],
            [ 'id'=> 282, 'fullName'=> 'Ahmed', 'email'=> 'necib119@gmail.com'],
            [ 'id'=> 283, 'fullName'=> 'Bellil djamila', 'email'=> 'Inayadiams38@outlook.fr'],
            [ 'id'=> 284, 'fullName'=> 'Madani mustapha', 'email'=> 'Lions.enr@gmail.com'],
            [ 'id'=> 285, 'fullName'=> 'BELKHIRI Salim', 'email'=> 'belkhiris042@gmail.com'],
            [ 'id'=> 286, 'fullName'=> 'Awwainat Loai', 'email'=> 'hinde.ittobane@gmail.com'],
            [ 'id'=> 287, 'fullName'=> 'Toutaou adel', 'email'=> 'toutaouadel@yahoo.fr'],
            [ 'id'=> 288, 'fullName'=> 'Aek', 'email'=> 'kamiliafaryati@gmail.com'],
            [ 'id'=> 289, 'fullName'=> 'Tayou Melyssa', 'email'=> 'mely.tayou@gmail.com'],
            [ 'id'=> 290, 'fullName'=> 'Brahim', 'email'=> 'yamina.mokhbi@yahoo.com'],
            [ 'id'=> 291, 'fullName'=> 'Zemouli Reda', 'email'=> 'reda04041977@gmail.com'],
            [ 'id'=> 292, 'fullName'=> 'Zemouli reda', 'email'=> 'Reda04041977@gemail.com'],
            [ 'id'=> 293, 'fullName'=> 'Kerbadji yessif', 'email'=> 'ykerbadji@yahoo.com'],
            [ 'id'=> 294, 'fullName'=> 'Mahmoudi Yasine', 'email'=> 'yasine.mahmoudi@laposte.net'],
            [ 'id'=> 295, 'fullName'=> 'DKHILI HASSEN', 'email'=> 'salwaayadi@yahoo.fr'],
            [ 'id'=> 296, 'fullName'=> 'Himoura walid', 'email'=> 'himourawalid@gmail.com'],
            [ 'id'=> 297, 'fullName'=> 'Sultan Ahmad', 'email'=> 'aasultan2018@gmail.com'],
            [ 'id'=> 298, 'fullName'=> 'KHIATI Abdelkader', 'email'=> 'k2r.khiati@gmail.com'],
            [ 'id'=> 299, 'fullName'=> 'Belalia mhamed', 'email'=> 'mhamedmamed02@gmail.com'],
            [ 'id'=> 300, 'fullName'=> 'BHIRI Ridha', 'email'=> 'smalt27@gmail.com'],
            [ 'id'=> 301, 'fullName'=> 'Haffaf sidi Mohamed imad', 'email'=> 'sanaa.blk1984@gmail.com'],
            [ 'id'=> 302, 'fullName'=> 'Haffaf sidi Mohamed imed', 'email'=> 'haffafimmade@gmail.com'],
            [ 'id'=> 303, 'fullName'=> 'El baderi', 'email'=> 'jamaltokyo22@gml.com'],
            [ 'id'=> 304, 'fullName'=> 'Ouadoudi Aziz', 'email'=> 'jammal.alae@gmail.com'],
            [ 'id'=> 305, 'fullName'=> 'Salem omar', 'email'=> 'sofibat38@gmail.com'],
            [ 'id'=> 306, 'fullName'=> 'Draz Muhammad said', 'email'=> 'imi.mania91@gmail.com'],
            [ 'id'=> 307, 'fullName'=> 'Taibi kamel', 'email'=> 'anissaguellout@gmail.com'],
            [ 'id'=> 308, 'fullName'=> 'Chaouch Abderrahmane', 'email'=> 'Chaouch38@hotmail.fr'],
            [ 'id'=> 309, 'fullName'=> 'Makhlouf Hamza', 'email'=> 'sara.mammeri@live.fr'],
            [ 'id'=> 310, 'fullName'=> 'Louriki al hassania', 'email'=> 'zitounih46@gmail.com'],
            [ 'id'=> 311, 'fullName'=> 'Djerbi mhamed', 'email'=> 'mhameddjerbi@yahoo.fr'],
            [ 'id'=> 312, 'fullName'=> 'Latreche maamar ', 'email'=> 'khalida.zah38@hotmail.fr'],
            [ 'id'=> 313, 'fullName'=> 'zanzoune reddade', 'email'=> 'reddade@hotmail.fr'],
            [ 'id'=> 314, 'fullName'=> 'ROBAIA Abdallah ', 'email'=> 'leilarobaia@gmail.com'],
            [ 'id'=> 315, 'fullName'=> 'Firas lachhab', 'email'=> 'lachhab_firas@hotmail.fr'],
            [ 'id'=> 316, 'fullName'=> 'Bachir elezaar Abderrahman ', 'email'=> 'krimbach38@gmail.com'],
            [ 'id'=> 317, 'fullName'=> 'Marir Farid ', 'email'=> 'faridmarir@yahoo.fr'],
            [ 'id'=> 318, 'fullName'=> 'Cisse Abdoulaye ', 'email'=> 'cisse63a@live.fr'],
            [ 'id'=> 319, 'fullName'=> 'Chabert Ludovic ', 'email'=> 'lchabert@protonmail.com'],
            [ 'id'=> 320, 'fullName'=> 'Ajbili Mohamed ', 'email'=> 'ajbili-momo@hotmail.com'],
            [ 'id'=> 321, 'fullName'=> 'Aid djamalle', 'email'=> 'nassim764@hotmail.fr'],
            [ 'id'=> 322, 'fullName'=> 'Haddad Hassan', 'email'=> 'haddadaya58@gmail.com'],
            [ 'id'=> 323, 'fullName'=> 'Fkiri anis', 'email'=> 'amira89ayadi@gmail.com'],
            [ 'id'=> 324, 'fullName'=> 'REDJIMI Sabri ', 'email'=> 'mb2014@gmx.fr'],
            [ 'id'=> 325, 'fullName'=> 'Benyettou tayeb', 'email'=> 'tayeb.benyettou38000@gmail.com'],
            [ 'id'=> 326, 'fullName'=> 'Mohamed Meddah ', 'email'=> 'meddahmohamed38@gmail.com'],
            [ 'id'=> 327, 'fullName'=> 'Abdelalitif ', 'email'=> 'djamel.abdelatif13@hotmail.com'],
            [ 'id'=> 328, 'fullName'=> 'Saidi Hamid ', 'email'=> 'echirolles_38@hotmail.fr'],
            [ 'id'=> 329, 'fullName'=> 'Al Hassan', 'email'=> 'abourkhaaicha@gmail.com'],
            [ 'id'=> 330, 'fullName'=> 'Betka mohamed', 'email'=> '21.bmohamed@gmail.com'],
            [ 'id'=> 331, 'fullName'=> 'Bahba Abdallah ', 'email'=> 'abdallah.bahba@laposte.net'],
            [ 'id'=> 332, 'fullName'=> 'Belalia mhamed', 'email'=> 'zibouchecharifa@gmail.com'],
            [ 'id'=> 333, 'fullName'=> 'GUELLOUT ABDELMALEK', 'email'=> 'malek.guellout@laposte.net'],
            [ 'id'=> 334, 'fullName'=> 'Tehari ', 'email'=> 'benoudatehari@gmail.com'],
            [ 'id'=> 335, 'fullName'=> 'Liacha fouad', 'email'=> 'liacha38@gmail.com'],
            [ 'id'=> 336, 'fullName'=> 'Ayari rached', 'email'=> 'just.rached@gmail.com'],
            [ 'id'=> 337, 'fullName'=> 'Maguenni abdelhadi', 'email'=> 'Abdelhadi.maguenni@gmail.com'],
            [ 'id'=> 338, 'fullName'=> 'Benreguieg Houari ', 'email'=> 'houaribeng31@gmail.com'],
            [ 'id'=> 339, 'fullName'=> 'Benmoussa mahi Nasser', 'email'=> 'benmahinasser@gmail.com'],
            [ 'id'=> 340, 'fullName'=> 'Grabsi salah eddine ', 'email'=> 'didinedidine2538@gmail.com'],
            [ 'id'=> 341, 'fullName'=> 'Serrag kheir-eddine ', 'email'=> 'seddine@gmail.com'],
            [ 'id'=> 342, 'fullName'=> 'Chiheb adel', 'email'=> 'yasminachiheb38@gmail.com'],
            [ 'id'=> 343, 'fullName'=> 'Reguigue Samir ', 'email'=> 'snako38@gmail.com'],
            [ 'id'=> 344, 'fullName'=> 'Louraichia ', 'email'=> 'inestoumi8@gmail.com'],
            [ 'id'=> 345, 'fullName'=> 'El houari gharib ', 'email'=> 'mastadoudou32@gmail.com'],
            [ 'id'=> 346, 'fullName'=> 'CHEIKHMOUSSA ', 'email'=> 'cheikhmoussamina@icloud.com'],
            [ 'id'=> 347, 'fullName'=> 'HELAOUI Amar', 'email'=> 'ammar.he@hotmail.com'],
            [ 'id'=> 348, 'fullName'=> 'Benchehida abdelkarim ', 'email'=> 'karimbenchehida00@gmail.com'],
            [ 'id'=> 349, 'fullName'=> 'Omarouayache Mustapha', 'email'=> 'mustapha.omarouayache@yahoo.fr'],
            [ 'id'=> 350, 'fullName'=> 'Bouslama khaled ', 'email'=> 'abdelhafidkhaled8@gmail.com'],
            [ 'id'=> 351, 'fullName'=> 'Dridi Abdelmalek ', 'email'=> 'abdelmalek-dridi@hotmail.com'],
            [ 'id'=> 352, 'fullName'=> 'Chaari imed', 'email'=> 'skendersahara@gmail.com'],
            [ 'id'=> 353, 'fullName'=> 'NAIB ', 'email'=> 'emma.zerrouki@gmail.com'],
            [ 'id'=> 354, 'fullName'=> 'Belarbi mustapha ', 'email'=> 'nadiabelarbi38@gmail.com'],
            [ 'id'=> 355, 'fullName'=> 'Lassar/ Damene Fatima', 'email'=> 'damenefatima01@gmail.com'],
            [ 'id'=> 356, 'fullName'=> 'Mhamdi  Hocine ', 'email'=> 'zaki.mhamdi38@gmail.com'],
            [ 'id'=> 357, 'fullName'=> 'Hedli hocine ', 'email'=> 'hocinehedli@yahoo.fr'],
            [ 'id'=> 358, 'fullName'=> 'NASRI fares', 'email'=> 'faressoni@outlook.fr'],
            [ 'id'=> 359, 'fullName'=> 'ABADA FOUZIA', 'email'=> 'fouzkai210@gmail.com'],
            [ 'id'=> 360, 'fullName'=> 'Addad zina', 'email'=> 'mimikadi92@gmail.com'],
            [ 'id'=> 361, 'fullName'=> 'Ahcene djaballah Mounira', 'email'=> 'kenzomounira@gmail.com'],
            [ 'id'=> 362, 'fullName'=> 'Ait lhoussaine Keltoum', 'email'=> 'tigmi38@gmail.com'],
            [ 'id'=> 363, 'fullName'=> 'Akerma yasmina', 'email'=> 'yasmina-38@live.fr'],
            [ 'id'=> 364, 'fullName'=> 'Amir Hanane', 'email'=> 'midounaimleen@gmail.com'],
            [ 'id'=> 365, 'fullName'=> 'Amayeva Maryam', 'email'=> 'famille38800@gmail.com'],
            [ 'id'=> 366, 'fullName'=> 'BAADACHE SABRINA', 'email'=> 'sabrinachaabia@gmail.com'],
            [ 'id'=> 367, 'fullName'=> 'Elarfaouia Mansoura', 'email'=> 'mansouraarfaouia@gmail.com'],
            [ 'id'=> 368, 'fullName'=> 'Khelifa Karima', 'email'=> 'balouma.karima@hotmail.fr'],
            [ 'id'=> 369, 'fullName'=> 'Beghila karima', 'email'=> 'beghilasajda@gmail.com'],
            [ 'id'=> 370, 'fullName'=> 'BEL HADJ SOFIA', 'email'=> 'myangel38@hotmail.fr'],
            [ 'id'=> 371, 'fullName'=> 'Khattab Fatima zahra', 'email'=> 'ad_malherbe@outlook.fr'],
            [ 'id'=> 372, 'fullName'=> 'belhadji Nadia', 'email'=> 'azibi.nadia@gamil.com'],
            [ 'id'=> 373, 'fullName'=> 'belhadji Nadia', 'email'=> 'azibi.nadia@gmail.com'],
            [ 'id'=> 374, 'fullName'=> 'Benaboura fatima zohra', 'email'=> 'Fatima07zohra@outlook.fr'],
            [ 'id'=> 375, 'fullName'=> 'Benaissa hassina', 'email'=> 'hassina.donia@yahoo.fr'],
            [ 'id'=> 376, 'fullName'=> 'Benameur Zahra', 'email'=> 'z.benhamou@laposte.net'],
            [ 'id'=> 377, 'fullName'=> 'Benatitallah Nacira', 'email'=> 'myriem19@hotmail.com'],
            [ 'id'=> 378, 'fullName'=> 'Benayache habiba', 'email'=> 'habiba.benayache@yahoo.fr'],
            [ 'id'=> 379, 'fullName'=> 'Sebti Manal', 'email'=> 'manalkenzi@hotmail.fr'],
            [ 'id'=> 380, 'fullName'=> 'Benkhrourou Fatima', 'email'=> 'lashab.f@gmail.com'],
            [ 'id'=> 381, 'fullName'=> 'Benkrama zaza', 'email'=> 'zaza.benkrama.zb@gmail.com'],
            [ 'id'=> 382, 'fullName'=> 'Benseghir karen', 'email'=> 'karen.benseghir@gmail.com'],
            [ 'id'=> 383, 'fullName'=> 'Benyettou Nadia', 'email'=> 'Nadia.boucebha87@gmail.com'],
            [ 'id'=> 384, 'fullName'=> 'BIRCH Houria', 'email'=> 'birch.houria@yahoo.fr'],
            [ 'id'=> 385, 'fullName'=> 'Ajaoun hafida', 'email'=> 'AJAOUN.38@gmail.com'],
            [ 'id'=> 386, 'fullName'=> 'Ajaoun hafida', 'email'=> 'AJAOUN.38@GMAIL.COM'],
            [ 'id'=> 387, 'fullName'=> 'Zohra Boubtane', 'email'=> 'zohra.boubtane@gmail.com'],
            [ 'id'=> 388, 'fullName'=> 'Boughraira ioana', 'email'=> 'andreeaboughraira@yahoo.com'],
            [ 'id'=> 389, 'fullName'=> 'Bouhalla Nabila', 'email'=> 'oumsiriya@hotmail.fr'],
            [ 'id'=> 390, 'fullName'=> 'Bouissa Hayat', 'email'=> 'hayat.bouissa@gmail.com'],
            [ 'id'=> 391, 'fullName'=> 'Buaissa zakia', 'email'=> 'bouissazakia@gmail.com'],
            [ 'id'=> 392, 'fullName'=> 'Boukelsous Samia', 'email'=> 'samiaboukelsous@yahoo.fr'],
            [ 'id'=> 393, 'fullName'=> 'Boulmrdais khalida', 'email'=> 'Khalidaboulmedais1983@gmail.com'],
            [ 'id'=> 394, 'fullName'=> 'Boutahra hanene', 'email'=> 'hananeboutahra30@gmail.com'],
            [ 'id'=> 395, 'fullName'=> 'Boutahra Nouria', 'email'=> 'boutahranouria@yahoo.fr'],
            [ 'id'=> 396, 'fullName'=> 'Bouti mouna', 'email'=> 'mounabouti@yahoo.com'],
            [ 'id'=> 397, 'fullName'=> 'Bouzzine Fatiha', 'email'=> 'ajalman.b@gmail.com'],
            [ 'id'=> 398, 'fullName'=> 'Ajalman Asmae', 'email'=> 'asmae.bouzzine@gmail.com'],
            [ 'id'=> 399, 'fullName'=> 'Chaouch hassiba', 'email'=> 'hassiba38@hotmail.fr'],
            [ 'id'=> 400, 'fullName'=> 'Charef Djamila', 'email'=> 'touha00b@gmail.com'],
            [ 'id'=> 401, 'fullName'=> 'Chekri chahinez', 'email'=> 'chahinezaous@yahoo.fr'],
            [ 'id'=> 402, 'fullName'=> 'Chikh karima', 'email'=> 'ferdaousalae@hotmail.com'],
            [ 'id'=> 403, 'fullName'=> 'Rihab Chtioui zammit', 'email'=> 'riribaya38@gmail.com'],
            [ 'id'=> 404, 'fullName'=> 'Oral Hatice', 'email'=> 'oral.hatice@hotmail.fr'],
            [ 'id'=> 405, 'fullName'=> 'Dahi Widad', 'email'=> 'haliwid@gmail.com'],
            [ 'id'=> 406, 'fullName'=> 'Dahouas ratiba', 'email'=> 'ratiba1262@gmail.com'],
            [ 'id'=> 407, 'fullName'=> 'DAOUD BRIKCI KHADIDJA', 'email'=> 'khadij.daoudbrikci@hotmail.fr'],
            [ 'id'=> 408, 'fullName'=> 'debit salma', 'email'=> 'salmadebit1986@gmail.com'],
            [ 'id'=> 409, 'fullName'=> 'Dellaa souhila', 'email'=> 'souhiladellaa@gmail.com'],
            [ 'id'=> 410, 'fullName'=> 'Derares kheira', 'email'=> 'kderares@gmail.com'],
            [ 'id'=> 411, 'fullName'=> 'OULD KACI', 'email'=> 'sabrinaouldkaci8@gmail.com'],
            [ 'id'=> 412, 'fullName'=> 'Djelailia', 'email'=> 'ameldih80@gmail.com'],
            [ 'id'=> 413, 'fullName'=> 'Djelili Souaad', 'email'=> 'souaad.djelili@gmail.com'],
            [ 'id'=> 414, 'fullName'=> 'DJELLOUL mazouz fatima', 'email'=> 'Louaygf38@gmail.com'],
            [ 'id'=> 415, 'fullName'=> 'El Aallami Elhame', 'email'=> 'elhameboubou38@gmail.com'],
            [ 'id'=> 416, 'fullName'=> 'El Hasni Imane', 'email'=> 'ettamouhimane@gmail.com'],
            [ 'id'=> 417, 'fullName'=> 'El mimouni zohra', 'email'=> 'abdel_3838@hotmail.fr'],
            [ 'id'=> 418, 'fullName'=> 'EL RHAFFARI ANISSA', 'email'=> 'anissaelrhaffari@hotmail.com'],
            [ 'id'=> 419, 'fullName'=> 'Farah latifa', 'email'=> 'latifafarah4545@gmail.com'],
            [ 'id'=> 420, 'fullName'=> 'Mme Farah Laila', 'email'=> 'farah.laila38@gmail.com'],
            [ 'id'=> 421, 'fullName'=> 'Ferdji amina', 'email'=> 'ferdjiamina@gmail.com'],
            [ 'id'=> 422, 'fullName'=> 'Gasmi Nawel', 'email'=> 'nawel.neffoussi@yahoo.fr'],
            [ 'id'=> 423, 'fullName'=> 'GHILOUFI Wafa', 'email'=> 'ghiloufiwafa@gmail.com'],
            [ 'id'=> 424, 'fullName'=> 'Ghoulem faiza', 'email'=> 'fgh38100@outlook.fr'],
            [ 'id'=> 425, 'fullName'=> 'GOURARI Nabila', 'email'=> 'gourari.nabila13@gmail.com'],
            [ 'id'=> 426, 'fullName'=> 'OUMEDDOUR RADHIA', 'email'=> 'radhiaoumeddour@yahoo.fr'],
            [ 'id'=> 427, 'fullName'=> 'Guedouar Hanane', 'email'=> 'ghoutta@gmail.com'],
            [ 'id'=> 428, 'fullName'=> 'Hadj mokhnache djamila', 'email'=> 'djourihadj15@gmail.com'],
            [ 'id'=> 429, 'fullName'=> 'Hakach hakima', 'email'=> 'hakachhakima@gmail.com'],
            [ 'id'=> 430, 'fullName'=> 'Hamada Kenza', 'email'=> 'yamineh38@gmail.com'],
            [ 'id'=> 431, 'fullName'=> "S'lamat fatima", 'email'=> 'slamat@hotmail.it'],
            [ 'id'=> 432, 'fullName'=> 'Harabi Dalila', 'email'=> 'dalila.hd@outlook.fr'],
            [ 'id'=> 433, 'fullName'=> 'Motam Naima', 'email'=> 'naimamotam04@gmail.com'],
            [ 'id'=> 434, 'fullName'=> 'Hemaizia, Karima', 'email'=> 'dalya13@live.fr'],
            [ 'id'=> 435, 'fullName'=> 'Kaidat djalila', 'email'=> 'kaidatratiba@gmail.com'],
            [ 'id'=> 436, 'fullName'=> 'Karrouby souad', 'email'=> 'narcisse31@live.fr'],
            [ 'id'=> 437, 'fullName'=> 'Kerfah Fatima', 'email'=> 'kerfahassia19@gmail.com'],
            [ 'id'=> 438, 'fullName'=> 'Lamia', 'email'=> 'lammiadz@gmail.com'],
            [ 'id'=> 439, 'fullName'=> 'Ketroussi kheira', 'email'=> 'bahi38100@gmail.com'],
            [ 'id'=> 440, 'fullName'=> 'Mejieva Elizaveta', 'email'=> 'boukall86@gmail.com'],
            [ 'id'=> 441, 'fullName'=> 'Khalissa verane', 'email'=> 'shaimakoum@gmail.com'],
            [ 'id'=> 442, 'fullName'=> 'Kheddim kalima', 'email'=> 'kali38@gmx.fr'],
            [ 'id'=> 443, 'fullName'=> 'Dahamni assia', 'email'=> 'assiadahamni07@gmail.com'],
            [ 'id'=> 444, 'fullName'=> 'Khiat naziha', 'email'=> 'ishakzakaria703@gmail.com'],
            [ 'id'=> 445, 'fullName'=> 'Khoualdi Naziha', 'email'=> 'khoualdian@yahoo.fr'],
            [ 'id'=> 446, 'fullName'=> 'Korichi Aicha', 'email'=> 'aichali.kor@gmail.com'],
            [ 'id'=> 447, 'fullName'=> 'Hassani hadjer', 'email'=> 'joujouhass38@gmail.com'],
            [ 'id'=> 448, 'fullName'=> 'Messairia Hamida', 'email'=> 'hamidarahman79@yahoo.com'],
            [ 'id'=> 449, 'fullName'=> 'Krour Samira', 'email'=> 'mohamedkrour076@gmail.com'],
            [ 'id'=> 450, 'fullName'=> 'Lachhab Hajar', 'email'=> 'hajar.elkhamlichii@gmail.com'],
            [ 'id'=> 451, 'fullName'=> 'Nadi souad', 'email'=> 'nadisouad1@gmail.com'],
            [ 'id'=> 452, 'fullName'=> 'Rotgang christina', 'email'=> 'dinarotgang@glail.comp'],
            [ 'id'=> 453, 'fullName'=> 'Bouchra Maguenni', 'email'=> 'bicha.kaouche.31@gmail.com'],
            [ 'id'=> 454, 'fullName'=> 'Mallek assia', 'email'=> 'assia.assia30@yahoo.com'],
            [ 'id'=> 455, 'fullName'=> 'Meftah Lemya', 'email'=> 'abid_lemya@yahoo.fr'],
            [ 'id'=> 456, 'fullName'=> 'Mendour bouchra', 'email'=> 'rababmendour@gmail.com'],
            [ 'id'=> 457, 'fullName'=> 'Mesbah yasmina', 'email'=> 'mesbah.yasmina@hotmail.fr'],
            [ 'id'=> 458, 'fullName'=> 'Bouchakour Anissa', 'email'=> 'anissa3808@gmail.com'],
            [ 'id'=> 459, 'fullName'=> 'MOKADEM', 'email'=> 'souhilamaster31@gmail.com'],
            [ 'id'=> 460, 'fullName'=> 'Sanaa el ahrache', 'email'=> 'sabrineaya12@gmail.com'],
            [ 'id'=> 461, 'fullName'=> 'Shairat ouafae', 'email'=> 'wafae.shairat@gmail.com'],
            [ 'id'=> 462, 'fullName'=> 'Loubna oudani', 'email'=> 'loubna.oudani1@gmail.com'],
            [ 'id'=> 463, 'fullName'=> 'Nasra mokhtaria', 'email'=> 'mokhtariaoran@hotmail.com'],
            [ 'id'=> 464, 'fullName'=> 'Salhi Selma', 'email'=> 'madamenazar@gmail.com'],
            [ 'id'=> 465, 'fullName'=> "N'DIAYE Nassita", 'email'=> 'nassita53@hotmail.fr'],
            [ 'id'=> 466, 'fullName'=> 'Nini salma', 'email'=> 'nini.amira05@gmail.com'],
            [ 'id'=> 467, 'fullName'=> 'OUZAA Ahlem', 'email'=> 'ouzaa.ahlem@gmail.com'],
            [ 'id'=> 468, 'fullName'=> 'Rached Saliha', 'email'=> 'rached.saliha@hotmail.fr'],
            [ 'id'=> 469, 'fullName'=> 'Rahlaoui fatiha', 'email'=> 'rahlaoui.fatiha@gmail.com'],
            [ 'id'=> 470, 'fullName'=> 'RAHMOUN Ahlam', 'email'=> 'ahlam.roudayna.rahmoun@gmail.com'],
            [ 'id'=> 471, 'fullName'=> 'Hedia rebai', 'email'=> 'rebai.hedia38@gmail.com'],
            [ 'id'=> 472, 'fullName'=> 'Reffass Mouna', 'email'=> 'mouna.reffass@yahoo.com'],
            [ 'id'=> 473, 'fullName'=> 'Henniche hakima', 'email'=> 'hennichehakima@gmail.com'],
            [ 'id'=> 474, 'fullName'=> 'Rettab halima', 'email'=> 'rettabhalima@gmail.com'],
            [ 'id'=> 475, 'fullName'=> 'Robaia malika', 'email'=> 'marley.cat@live.fr'],
            [ 'id'=> 476, 'fullName'=> 'Safra Houyem', 'email'=> 'houyam2009@Hotmail.com'],
            [ 'id'=> 477, 'fullName'=> 'Safra Houyem', 'email'=> 'houyam2009@hotmail.com'],
            [ 'id'=> 478, 'fullName'=> 'Sahi Malika', 'email'=> 'malika.sahi@gmail.com'],
            [ 'id'=> 479, 'fullName'=> 'Chitamurova kheda', 'email'=> 'khedachitamurova@gmail.com'],
            [ 'id'=> 480, 'fullName'=> 'Sansri monia', 'email'=> 'mayssandania29@yahoo.com'],
            [ 'id'=> 481, 'fullName'=> 'hafsaoui fatima', 'email'=> 'hafsaouifatima3@gmail.com'],
            [ 'id'=> 482, 'fullName'=> 'Frites Fouzia', 'email'=> 'faizaramy38@gmail.com'],
            [ 'id'=> 483, 'fullName'=> 'Dridi Nadia', 'email'=> 'nadiadri@outlook.fr'],
            [ 'id'=> 484, 'fullName'=> 'Tazghat Nadjat', 'email'=> 'kemal_algerie@hotmail.com'],
            [ 'id'=> 485, 'fullName'=> 'tennah kaoutar', 'email'=> 'douachkaoutar@gmail.com'],
            [ 'id'=> 486, 'fullName'=> 'Teriki fedwa', 'email'=> 'fedhamiditer@gmail.com'],
            [ 'id'=> 487, 'fullName'=> 'Torchi', 'email'=> 'haddatorchi2@gmail.com'],
            [ 'id'=> 488, 'fullName'=> 'metkal latifa', 'email'=> 'wifaknora18@gmail.com'],
            [ 'id'=> 489, 'fullName'=> 'metkal latifa', 'email'=> 'wifaknora18@gmail.fr'],
            [ 'id'=> 490, 'fullName'=> 'Lamia', 'email'=> 'el.lamiaa123@gmail.com'],
            [ 'id'=> 491, 'fullName'=> 'Yessad Hadjer', 'email'=> 'yessadhadjer4@gmail.com'],
            [ 'id'=> 492, 'fullName'=> 'Ykhlef Imane', 'email'=> 'imane38100@yahoo.fr'],
            [ 'id'=> 493, 'fullName'=> 'Zitouni Kheira', 'email'=> 'medanik@yahoo.com'],
            [ 'id'=> 494, 'fullName'=> 'haroune dalila', 'email'=> 'jyadkossay@gmail.com'],
            [ 'id'=> 495, 'fullName'=> 'Benahmed Djahida', 'email'=> 'benahmeddjahida3@gmail.com'],
            [ 'id'=> 496, 'fullName'=> 'Chaloum Djouweyda', 'email'=> 'jijiyoyo3800@gmail.com'],
            [ 'id'=> 497, 'fullName'=> 'Diaby Gondoba', 'email'=> 'gondoba.diaby@gmail.com'],
            [ 'id'=> 498, 'fullName'=> 'Guenniche Sandra', 'email'=> 'sandraguenniche5@gmail.com'],
            [ 'id'=> 499, 'fullName'=> 'Merimi amina', 'email'=> 'massir123am@gmail.com'],
            [ 'id'=> 500, 'fullName'=> 'Chouayet radhia', 'email'=> 'chouayetradhia@gmail.com'],
            [ 'id'=> 501, 'fullName'=> 'AZIBI FARIDA', 'email'=> 'azibi.farida@gmail.com'],
            [ 'id'=> 502, 'fullName'=> 'Leuci Ines', 'email'=> 'ines_assia@hotmail.fr'],
            [ 'id'=> 503, 'fullName'=> 'Majidi amal', 'email'=> 'amalaitsaid33@gmail.com'],
            [ 'id'=> 504, 'fullName'=> 'Tebib Soumeya', 'email'=> 'soumeya.tebib@gmail.com'],
            [ 'id'=> 505, 'fullName'=> 'Kadri Rania', 'email'=> 'raniakadri4@gmail.col'],
            [ 'id'=> 506, 'fullName'=> 'Guitoun karima', 'email'=> '1.guitounkarima@gmail.com'],
            [ 'id'=> 507, 'fullName'=> 'Bouzerara Samah', 'email'=> 'Bouzerarasamah@gmail.com'],
            [ 'id'=> 508, 'fullName'=> 'Boudour manel', 'email'=> 'boudourmanel8@gmail.com'],
            [ 'id'=> 509, 'fullName'=> 'Hammoudy samira', 'email'=> 'samira.atioui23@gmail.com'],
            [ 'id'=> 510, 'fullName'=> 'Medjahed Djemaia', 'email'=> 'medjahed38000@gmail.com'],
            [ 'id'=> 511, 'fullName'=> 'Sara Faraj', 'email'=> 'farajsarah@hotmail.com'],
            [ 'id'=> 512, 'fullName'=> 'Aboubacar Halima Ibrahim', 'email'=> 'halima.aboubacar@ymail.com'],
            [ 'id'=> 513, 'fullName'=> 'Lakehal caroline', 'email'=> 'monteirocaroline@hotmail.fr'],
            [ 'id'=> 514, 'fullName'=> 'ALKADRI Samah', 'email'=> 'Samah.alkadri@outlook.com'],
            [ 'id'=> 515, 'fullName'=> 'francesca gramegna', 'email'=> 'francesca_g_90@hotmail.it'],
            [ 'id'=> 516, 'fullName'=> 'Benali Ouarda', 'email'=> 'benaliouarda0@gmail.com'],
            [ 'id'=> 517, 'fullName'=> 'Kaddar Nabila', 'email'=> 'sarakaddar8@gmail.com'],
            [ 'id'=> 518, 'fullName'=> 'Ghattas lama', 'email'=> 'ghattas.lama@gmail.com'],
            [ 'id'=> 519, 'fullName'=> 'Sedki Fatima', 'email'=> 'Fatima.elazraki@yahoo.fr'],
            [ 'id'=> 520, 'fullName'=> 'Adjadj Rabab', 'email'=> 'assil.boulahia@gmail.com'],
            [ 'id'=> 521, 'fullName'=> 'Niati fatiha', 'email'=> 'fatihaniati.1082@gmail.com'],
            [ 'id'=> 522, 'fullName'=> 'DAOUDI Ikram', 'email'=> 'fbdu73@gmail.com'],
            [ 'id'=> 523, 'fullName'=> 'Bouziane maroua', 'email'=> 'marouabouzine24@gmail.com'],
            [ 'id'=> 524, 'fullName'=> 'Fedila farah', 'email'=> 'farah.31@hotmail.fr'],
            [ 'id'=> 525, 'fullName'=> 'Abir', 'email'=> 'nacib.abir@gmail.com'],
            [ 'id'=> 526, 'fullName'=> 'Fatmi chahinaz', 'email'=> 'fatmi.chahinez@gmail.com'],
            [ 'id'=> 527, 'fullName'=> 'BELKHIRI SABRINE', 'email'=> 'belkhirimalak0@gmail.com'],
            [ 'id'=> 528, 'fullName'=> 'Talhaoui alia', 'email'=> 'talhaouialia@yahoo.fr'],
            [ 'id'=> 529, 'fullName'=> 'Zemouli mouna', 'email'=> 'mouna25091986@gmail.com'],
            [ 'id'=> 530, 'fullName'=> 'Zemouli Mouna', 'email'=> 'Mouna25091986@gemail.com'],
            [ 'id'=> 531, 'fullName'=> 'Himoura Halima', 'email'=> 'halimahimoura@gmail.com'],
            [ 'id'=> 532, 'fullName'=> 'Sultan Soha', 'email'=> 'soha.souk@hotmail.com'],
            [ 'id'=> 533, 'fullName'=> 'GOUAICH Toutia', 'email'=> 'gouaichtoutia@gmail.com'],
            [ 'id'=> 534, 'fullName'=> 'SOR Marjorie', 'email'=> 'marjorie.sor@gmail.com'],
            [ 'id'=> 535, 'fullName'=> 'Salem yamina', 'email'=> 'sanah38@hotmail.fr'],
            [ 'id'=> 536, 'fullName'=> 'benyettou nadia', 'email'=> 'nadia.boucebha87@gmail.com'],
            [ 'id'=> 538, 'fullName'=> 'ROBAIA koria', 'email'=> 'leilarobaia@mail.com'],
            [ 'id'=> 539, 'fullName'=> 'Lachhab saida', 'email'=> 'benslimene.saida@gmail.com'],
            [ 'id'=> 540, 'fullName'=> 'Abdelli Lynda ', 'email'=> 'aigleblanc200975@yahoo.fr'],
            [ 'id'=> 541, 'fullName'=> 'Cisse Fatoumata ', 'email'=> 'fatoumata336@gmail.com'],
            [ 'id'=> 542, 'fullName'=> 'Chabert Azzouni Salima ', 'email'=> 'salima.chazz@outlook.com'],
            [ 'id'=> 543, 'fullName'=> 'Ajbili siham', 'email'=> 'nada-1907@hotmail.com'],
            [ 'id'=> 544, 'fullName'=> 'Haddad Fatima', 'email'=> 'fatima.haddad140@gmail.com'],
            [ 'id'=> 545, 'fullName'=> 'Fkiri amira', 'email'=> 'anis.fikiri@gmail.com'],
            [ 'id'=> 546, 'fullName'=> 'BEGUIN Maud', 'email'=> 'beguin.maud@sfr.fr'],
            [ 'id'=> 547, 'fullName'=> 'Benyettou aicha', 'email'=> 'aicha.benyettou@outlook.fr'],
            [ 'id'=> 548, 'fullName'=> 'Saidi Sihem ', 'email'=> 'sihem.drabni4@gmail.com'],
            [ 'id'=> 549, 'fullName'=> 'Bahba Émilie ', 'email'=> 'emilie.lecanu@hotmail.fr'],
            [ 'id'=> 550, 'fullName'=> 'Amer BENBEKRITE', 'email'=> 'hannabekhti2@gmail.com'],
            [ 'id'=> 551, 'fullName'=> 'Tehari nora', 'email'=> 'aichatehari@gmail.com'],
            [ 'id'=> 552, 'fullName'=> 'Boukhari Fatiha ', 'email'=> 'boukharifatiha@hotmail.fr'],

            [ 'id'=> 553, 'fullName'=> 'Salma Sonia ', 'email'=> 'selmayasser2016@gmail.com'],
            [ 'id'=> 554, 'fullName'=> 'Benmoussa Mahi mokhtaria ', 'email'=> 'mokhtariabenmoussa38@gmail.com'],
            [ 'id'=> 555, 'fullName'=> 'Grabsi houria ', 'email'=> 'grabsijannet@gmail.com'],
            [ 'id'=> 556, 'fullName'=> 'Serrag salah', 'email'=> 'semeh@hotmail.fr'],
            [ 'id'=> 557, 'fullName'=> 'Yazami meryem ', 'email'=> 'meryazami@gmail.com'],
            [ 'id'=> 558, 'fullName'=> 'El houari khadija ', 'email'=> 'khadoumaroc86@gmail.com'],
            [ 'id'=> 559, 'fullName'=> 'DJEBILI Linda', 'email'=> 'djelin@hotmail.com'],
            [ 'id'=> 560, 'fullName'=> 'Ghouli hadjira', 'email'=> 'ghoulihadjira3@gmail.com'],
            [ 'id'=> 561, 'fullName'=> 'Omarouayache Hadjer ', 'email'=> 'ayache.31hadjer@hotmail.com'],
            [ 'id'=> 562, 'fullName'=> 'Dridi Nada', 'email'=> 'nada-dridi@hotmail.fr'],
            [ 'id'=> 563, 'fullName'=> 'Senani sahra', 'email'=> 'Skendersahara@gmail.com'],
            [ 'id'=> 564, 'fullName'=> 'Mhamdi hala', 'email'=> 'halamhamdu@gmail.com'],
            [ 'id'=> 565, 'fullName'=> 'NASRI Amel ', 'email'=> 'benelhadj_amel@hotmail.fr'],*/
        ];
        foreach ($contacts as $contact) {
            dump($contact['email']);
            $email = $contact['email'];
            $this->mailService->sendEmail(
                to: $email,
                subject: 'Un Hajj d’Exception avec le Centre Culturel Ibn Badis et Dogane !',
                template: 'email/company/haj-2025.html.twig',
                context: [
                    'fullName' => $contact['fullName'],
                ],
                sender: "voyage@ccib38.com"
            );
        }

        $this->entityManager->flush();

        $io->success('All sessions have been created successfully!');

        return Command::SUCCESS;
    }
}
