# config/services.yaml

parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Command\:
        resource: '../src/Command'
        tags: [ 'console.command' ]
        autowire: true
        autoconfigure: true

    # Configuration du listener pour Doctrine
    App\EventListener\UserCreationListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'postPersist' }

    # Transformer enregistré comme service
    App\Form\DataTransformer\CommaSeparatedToArrayTransformer: ~
