# config/services.yaml

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Enregistrement du transformer en tant que service
    App\Form\DataTransformer\CommaSeparatedToArrayTransformer: ~
