name: Deploy to o2switch (Self-hosted)

on:
  push:
    branches: [ "master" ]    # change en "main" si besoin
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, deploy]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # On utilise le PHP/Composer déjà installés sur le runner
      - name: PHP/Composer versions
        run: |
          set -e
          php -v
          composer -V

      - name: Composer install (prod, no-scripts)
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-scripts

      # Node côté runner (yarn.lock présent -> Yarn)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & Build (Yarn or npm)
        run: |
          set -e
          if [ -f yarn.lock ]; then
            npm install -g yarn
            yarn install --frozen-lockfile
            yarn build
          else
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
            npm run build
          fi

      - name: Connectivity check
        run: nc -vz -w 5 turquoise.o2switch.net 22

      - name: Rsync to o2switch
        env:
          SSH_HOST: turquoise.o2switch.net
          SSH_USER: yiba1083
          SSH_PORT: 22
          REMOTE_PATH: /home/yiba1083/ecole.ccib38.fr/ccib38scholle
        run: |
          set -e
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "mkdir -p '$REMOTE_PATH'"
          rsync -az --delete -e "ssh -p $SSH_PORT" \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="node_modules" \
            --exclude="vendor" \
            --exclude="docker" \
            --exclude="docker-compose.yml" \
            --exclude="docker-compose.yaml" \
            --exclude="compose.override.yaml" \
            --exclude="tests" \
            --exclude="var/cache/*" \
            ./ "$SSH_USER@$SSH_HOST:$REMOTE_PATH"

      - name: Run post-deploy commands
        env:
          SSH_HOST: turquoise.o2switch.net
          SSH_USER: yiba1083
          SSH_PORT: 22
          REMOTE_PATH: /home/yiba1083/ecole.ccib38.fr/ccib38scholle
          APP_URL: https://ecole.ccib38.fr
        run: |
          set -e
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" bash -s <<'EOSH'
          set -e
          cd "$REMOTE_PATH"

          export APP_ENV=prod
          export APP_DEBUG=0
          export APP_URL="${APP_URL:-}"

          # Composer install dans le dossier du projet
          /usr/local/bin/php -d memory_limit=-1 $(which composer) install --no-dev --prefer-dist --optimize-autoloader --no-interaction

          # Commandes Symfony
          /usr/local/bin/php bin/console doctrine:migrations:migrate --no-interaction --env=prod
          /usr/local/bin/php bin/console cache:clear --env=prod
          /usr/local/bin/php bin/console cache:warmup --env=prod
          EOSH
      
