name: Deploy to o2switch (Self-hosted)

on:
  push:
    branches: [ "master" ]          # change en "main" si besoin
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, deploy]    # ← correspond aux labels de ton runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- PHP / Composer (on évite les scripts ici)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          coverage: none

      - name: Composer install (prod, no-scripts)
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-scripts

      # --- Front (Yarn prioritaire si yarn.lock, sinon npm)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & Build (Yarn or npm)
        run: |
          set -eu
          if [ -f yarn.lock ]; then
            npm install -g yarn
            yarn install --frozen-lockfile
            yarn build
          else
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
            npm run build
          fi

      # --- Sanity check réseau (facultatif)
      - name: Connectivity check
        run: nc -vz -w 5 turquoise.o2switch.net 22

      # --- Déploiement via rsync (utilise la clé ~/.ssh/id_ed25519 du runner)
      - name: Rsync to o2switch
        env:
          SSH_HOST: turquoise.o2switch.net
          SSH_USER: yiba1083
          SSH_PORT: 22
          REMOTE_PATH: /home/yiba1083/ecole.ccib38.fr/ccib38scholle
        run: |
          set -eu
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "mkdir -p '$REMOTE_PATH'"
          rsync -az --delete -e "ssh -p $SSH_PORT" \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="node_modules" \
            --exclude="vendor" \
            --exclude="docker" \
            --exclude="docker-compose.yml" \
            --exclude="docker-compose.yaml" \
            --exclude="compose.override.yaml" \
            --exclude="tests" \
            --exclude="var/cache/*" \
            ./ "$SSH_USER@$SSH_HOST:$REMOTE_PATH"

      # --- Post-deploy : composer (avec scripts), migrations, cache
      - name: Run post-deploy commands
        env:
          SSH_HOST: turquoise.o2switch.net
          SSH_USER: yiba1083
          SSH_PORT: 22
          REMOTE_PATH: /home/yiba1083/ecole.ccib38.fr/ccib38scholle
          APP_URL: https://ecole.ccib38.fr   # adapte si besoin (ou mets-le dans .env.local)
        run: |
          set -eu
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" bash -s <<'EOSH'
          set -eu
          cd "$REMOTE_PATH"
          export APP_ENV=prod
          export APP_DEBUG=0
          export APP_URL="${APP_URL:-}"
          /usr/local/bin/php -d memory_limit=-1 $(which composer) install --no-dev --prefer-dist --optimize-autoloader --no-interaction
          /usr/local/bin/php bin/console doctrine:migrations:migrate --no-interaction --env=prod
          /usr/local/bin/php bin/console cache:clear --env=prod
          /usr/local/bin/php bin/console cache:warmup --env=prod
          EOSH
